package org.birthday;

public class MoniBirthday {
public static void main(String[] args) throws InterruptedException {
	
	Thread.sleep(1000);
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH   	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHHHHHHHHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH    HHHH");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("       AA ");
	System.out.println("       AA");
	System.out.println("      AAAA");
	System.out.println("     AA  AA");
	System.out.println("    AA    AA");
	System.out.println("   AAAAAAAAAA");
	System.out.println("  AA        AA");
	System.out.println(" AA          AA");
	System.out.println("AA            AA");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PP        PP");
	System.out.println("PP        PP");
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PP        PP");
	System.out.println("PP        PP");
	System.out.println("PPPPPPPPPPPP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("PP");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println(" YY       YY");
	System.out.println(" YY       YY");
	System.out.println("  YY     YY");
	System.out.println("   YY   YY");
	System.out.println("    YYYYY");
	System.out.println("      YY");
	System.out.println("      YY");
	System.out.println("      YY");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("BBBBBBBBBBBBB");
	System.out.println("BB          BB");
	System.out.println("BB          BB");
	System.out.println("BBBBBBBBBBBB");
	System.out.println("BB          BB");
	System.out.println("BB          BB");
	System.out.println("BBBBBBBBBBBBB");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("IIIIIIIIIIIII");
	System.out.println("      II     ");
	System.out.println("      II     ");
	System.out.println("      II     ");
	System.out.println("      II     ");
	System.out.println("      II     ");
	System.out.println("IIIIIIIIIIIII");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("RRRRRRRRRRRRR");
	System.out.println("RR         RR");
	System.out.println("RR        RR");
	System.out.println("RRRRRRRRRRRR");
	System.out.println("RR        RR");
	System.out.println("RR         RR");
	System.out.println("RR          RR");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("TTTTTTTTTTTTT");
	System.out.println("      TT      ");
	System.out.println("      TT      ");
	System.out.println("      TT      ");
	System.out.println("      TT      ");
	System.out.println("      TT      ");
	System.out.println("      TT      ");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH   	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHHHHHHHHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH    HHHH");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("DDDDDDDDDDD");
	System.out.println("DD         D");
	System.out.println("DD          D");
	System.out.println("DD          D");
	System.out.println("DD          D");
	System.out.println("DD         D");
	System.out.println("DDDDDDDDDDD");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println("       AA ");
	System.out.println("       AA");
	System.out.println("      AAAA");
	System.out.println("     AA  AA");
	System.out.println("    AA    AA");
	System.out.println("   AAAAAAAAAA");
	System.out.println("  AA        AA");
	System.out.println(" AA          AA");
	System.out.println("AA            AA");
	System.out.println("\n");
	Thread.sleep(1000);
	System.out.println(" YY       YY");
	System.out.println(" YY       YY");
	System.out.println("  YY     YY");
	System.out.println("   YY   YY");
	System.out.println("    YYYYY");
	System.out.println("      YY");
	System.out.println("      YY");
	System.out.println("      YY");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("MM           MMMMM    ");
	System.out.println("MM  MM      MM    MM" );
	System.out.println("MM   MM    MM      MM");
	System.out.println("MM    MM  MM        MM");  
	System.out.println("MM     MMMM         MM ");
	System.out.println("MM                 MM   ");
	System.out.println("MM                MM");
	System.out.println("MM               MM");
	System.out.println("MM              MM");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("   OOOOOOOOOOOO  ");
	System.out.println("  OO          OO");
	System.out.println(" OO            OO");
	System.out.println("OO              OO");
	System.out.println("OO              OO");
	System.out.println(" OO            OO");
	System.out.println("  OO          OO");
	System.out.println("   OOOOOOOOOOOO  ");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("NNNN         NN");
	System.out.println("NN NN        NN");
	System.out.println("NN  NN       NN");
	System.out.println("NN   NN      NN");
	System.out.println("NN    NN     NN");
	System.out.println("NN     NN    NN");
	System.out.println("NN      NN   NN");
	System.out.println("NN        NN NN");
	System.out.println("NN         NNNN");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("IIIIIIIIIIIIIIII");
	System.out.println("       II     ");
	System.out.println("       II     ");
	System.out.println("       II     ");
	System.out.println("       II     ");
	System.out.println("       II     ");
	System.out.println("       II     ");
	System.out.println("IIIIIIIIIIIIIIII");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("   SSSSSSSSSSSSSSSS");
	System.out.println("  SS");
	System.out.println(" SS");
	System.out.println("SS");
	System.out.println(" SS");
	System.out.println("  SS");
	System.out.println("   SSSSSSSSSSSSSSSS");
	System.out.println("                  SS");
	System.out.println("                   SS");
	System.out.println("                    SS");
	System.out.println("                   SS");
	System.out.println("                  SS");
	System.out.println("   SSSSSSSSSSSSSSSS");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH   	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHHHHHHHHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH	HHHH");
	System.out.println("HHHH    HHHH");
	System.out.println("\n");
	Thread.sleep(1500);
	System.out.println("       AA ");
	System.out.println("       AA");
	System.out.println("      AAAA");
	System.out.println("     AA  AA");
	System.out.println("    AA    AA");
	System.out.println("   AAAAAAAAAA");
	System.out.println("  AA        AA");
	System.out.println(" AA          AA");
	System.out.println("AA            AA");
	Thread.sleep(3000);
	System.out.println("\n");
	System.out.println("\n");
	System.out.println("    ****          ****");
	System.out.println("   **    **   **     **");
	System.out.println("  **       ***        **");
	System.out.println("  **         *         **");
	System.out.println("  **      RANJITH      ** ");
	System.out.println("  **                   **");
	System.out.println("   **        MONI     ** ");
	System.out.println("     **              **");
	System.out.println( "      **           ** ");
	System.out.println("         **       **");
	System.out.println("           **    ** ");
	System.out.println("             ***");
	System.out.println("\n");
	System.out.println("\n");	
	Thread.sleep(3000);
	System.out.println("                              ~~");
	System.out.println("                              ||");
	System.out.println("                              ||");
	System.out.println("                       ~~~~~~~~~~~~~~~~");
	System.out.println("                      |                |");
	System.out.println("                      |  ONCE AGAIN    |");
	System.out.println("                   ___| ...............|___");
	System.out.println("                  |                        |        ");
	System.out.println("                  |    WISH YOU HAPPY      |");
	System.out.println("              ____|........................|____");
	System.out.println("             |                                  |");
	System.out.println("             |    BIRTHDAY TO MY EVERYTHING     |");
	System.out.println("             |__________________________________|");
	
	
	
	
	
	
}
}		